### ISSUE TITLE
Please make a new release

### ISSUE THREAD

**Issue by rapperskull** [emoose/xbox-winfsp#4]
It has been almost one year since the latest commit, but no new version was released. In the meanwhile, GitHub artifacts expired. I think a new release is needed.

**Comment by emoose** [comment]
Ah darn, didn't know artifacts would expire, thanks for letting me know. I'll push a new release soon, might look into your other issue #5 first though.

E: released 0.4 here: https://github.com/emoose/xbox-winfsp/releases/tag/0.4
